# Generated by Django 5.0.7 on 2024-09-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocks',
            field=models.JSONField(default=[]),
        ),
    ]
