# Generated by Django 5.0.7 on 2024-09-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blocks',
            field=models.JSONField(default=list),
        ),
    ]
