# Generated by Django 5.0.7 on 2024-09-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='childrens', to='posts.post'),
        ),
    ]
