# Generated by Django 5.0.7 on 2024-10-01 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_depth_post_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotes', to='posts.post'),
        ),
    ]
