# Generated by Django 5.0.7 on 2024-09-22 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(through='relations.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
