# Generated by Django 5.0.7 on 2024-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
