# Generated by Django 5.0.7 on 2024-09-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_large'),
        ('users', '0005_user_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
    ]
