# Generated by Django 5.0.7 on 2024-10-08 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_header_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('kakao', 'Kakao')], max_length=64)),
                ('provider_id', models.IntegerField()),
                ('provider_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
