# Generated by Django 5.0.7 on 2024-10-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_thirdpartyintegration_provider_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
