services:
  server: &server
    build: .
    container_name: bsky-backend
    # command: sh dev.sh runserver 0.0.0.0:8000
    command: tail -f /dev/null
    ports:
      - 8002:8000
    volumes:
      - .:/app
      - .vscode-server:/root/.vscode-server
    env_file:
      - ./.env
    healthcheck:
        test: ['CMD','curl','http://localhost:8002/']
        interval: 10s
        timeout: 5s
        retries: 2
        start_period: 5s
    restart: on-failure

  deploy:
    <<: *server
    container_name: cotton-backend
    ports:
     - ${port:-8000}:8000
    volumes:
      - .:/none
    entrypoint: sh run.sh
    healthcheck:
        test: ['CMD','curl','http://localhost:${port:-8000}/']
        interval: 10s
        timeout: 5s
        retries: 2
        start_period: 5s