# Generated by Django 5.0.7 on 2024-10-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attendants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direct_message', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendants', models.ManyToManyField(related_name='message_groups', through='chats.MessageAttendant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messageattendant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attendants', to='chats.messagegroup'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('identifier', models.CharField(max_length=63)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.messageattendant')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.messagegroup')),
            ],
        ),
        migrations.AddIndex(
            model_name='messageattendant',
            index=models.Index(fields=['group', 'user'], name='chats_messa_group_i_f901bb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['group', 'attendant', 'id'], name='chats_messa_group_i_373bd6_idx'),
        ),
    ]
