# Generated by Django 5.0.7 on 2024-10-04 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messageattendant',
            index=models.Index(fields=['user'], name='chats_messa_user_id_a60de2_idx'),
        ),
    ]
