# Generated by Django 5.0.7 on 2024-10-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_messagecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
