# Generated by Django 5.0.7 on 2024-10-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='character',
            field=models.TextField(default=''),
        ),
    ]
