# Generated by Django 5.0.7 on 2024-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_newscrawler'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='news_subscriptions',
            field=models.ManyToManyField(related_name='chatbots', to='ai.newscrawler'),
        ),
    ]
