# Generated by Django 5.0.7 on 2024-10-10 14:47

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chatbot_news_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscrawler',
            name='article_attrs',
            field=models.JSONField(default=ai.models.get_default_attrs),
        ),
    ]
