# Generated by Django 5.0.7 on 2024-10-02 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0010_post_quote'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('favorited_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_notifications', to='posts.favorite')),
                ('followed_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followed_notifications', to='relations.follow')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('mentioned_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_notifications', to='posts.mention')),
                ('quoted_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quoted_notifications', to='posts.post')),
                ('replied_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replied_notifications', to='posts.post')),
                ('reposted_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted_notifications', to='posts.repost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
