# Generated by Django 5.0.7 on 2024-10-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0010_post_quote'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='followed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_notifications', to='relations.follow'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='quoted_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quoted_notifications', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='replied_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_notifications', to='posts.post'),
        ),
    ]
